### ISSUE TITLE
Conventions definitions fail when using your package

### ISSUE THREAD

**Issue by Petteroe** [twenzel/NServiceBus.MSDependencyInjection#3]
Hi,
I tried your package today for setting up DI in a .Net Core 2.1 Console Application using your example as a start. When I did that, the conventions definitions started to fail. The Type that was fed into the conventions function is null. See screenshot.
Is this a known thing? How can I trace/test this to see where it fails?
Thanks,
Morten
![image](https://user-images.githubusercontent.com/5712277/46605561-35ea9180-cafa-11e8-943e-5d23dd55888e.png)

**Comment by Petteroe** [comment]
Update: The assemblies were still scanned, but it seems that more types were evaluated.

This change to the conventions definition seems to have fixed it:

`conventions.DefiningCommandsAs(types => types.Namespace?.EndsWith("Commands") ?? false);`

**Comment by twenzel** [comment]
This way to configure the conventions is common. I also check for empty/null namespace.
I guess some internal compiler generated types have no namespace.

This behavior is not specific to NServiceBus.MSDependencyInjection. It's general for all NServiceBus applications.
